version: 2

# Specify os and python version
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv run --no-sources python -m sphinx docs/source $READTHEDOCS_OUTPUT/html -b html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
