version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

  commands:
    - pixi run readthedocs

sphinx:
   configuration: docs/source/conf.py

conda:
  environment: ci/conda-envs/readthedocs.yml
