name: 'test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        environment: [py310, py311, py312, py313]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup environment
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          environments: ${{ matrix.environment }}

      - name: run pytests
        shell: bash -el {0}
        run: |
          pixi r test

  test-conda-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Conda build environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/conda-envs/mamba-build.yml

      - name: Build Conda package
        shell: bash -el {0}
        run: |
          conda mambabuild conda.recipe --output-folder pkgs/ -c usask-arg-nightly
